name: Pipeline for Shopping List

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build project
        run: dotnet build

      - name: Test project
        if: success()
        run: dotnet test

      - name: Print on Push
        if: ${{ github.event.push }}
        run: |
          echo "Push it real good!"
      
      - name: Print on Pull Request
        if: ${{ github.event.pull_request }}
        run: |
          echo "Some text"

      - name: Print on Workflow Dispatch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "This is being displayed when running the workflow manually..."
          echo "ğŸ”§ Running on OS: ${{ matrix.os }}"
          echo "ğŸ–¥ï¸ Using .NET version: ${{ matrix.version }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸ“‚ Worfklow: ${{ github.workflow }}"
          echo "ğŸš€ Triggered by: ${{ github.event_name }}"
          echo "ğŸ¥· Actor: ${{ github.actor }}"
          echo "ğŸ”¢ Run number: ${{ github.run_number }}"
          echo "ğŸŒ¿ Branch: ${{ github.ref }}"
