name: Pipeline for Shopping List

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build project
        run: dotnet build

      - name: Test project
        if: success()
        run: dotnet test

      - name: Print on Push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "ğŸ¥· Author: ${{ github.actor }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Files changed: $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)"

      - name: Print on Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Pull Request author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request number: ${{ github.event.pull_request.number }}"
          echo "Pull Request target source: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request target target: ${{ github.event.pull_request.base.ref }}"
          echo "Files changed: $(git diff --name-only HEAD^1 HEAD | xargs)"

      - name: Print on Workflow Dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "This is being displayed when running the workflow manually..."
          echo "ğŸ”§ Running on OS: ${{ matrix.os }}"
          echo "ğŸ–¥ï¸ Using .NET version: ${{ matrix.version }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸ“‚ Worfklow: ${{ github.workflow }}"
          echo "ğŸš€ Triggered by: ${{ github.event_name }}"
          echo "ğŸ¥· Actor: ${{ github.actor }}"
          echo "ğŸ”¢ Run number: ${{ github.run_number }}"
          echo "ğŸŒ¿ Branch: ${{ github.ref }}"
