name: Title breaker
on:
  pull_request:
    branches: main
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    outputs:
      test_result: ${{ steps.gen_build_outputs.outputs.test_result }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5   
        
      - name: setup NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{matrix.version}}

      - name: Build project
        run: dotnet build
      
      - name: Build Test
        id: gen_build_outputs
        if: success()
        shell: bash
        run: |
          version=$(dotnet test 2>&1)
          version=$(echo "$version" | tr '\n' ' ' | xargs)
          echo "test_result=$version" >> "$GITHUB_OUTPUT"

  
  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Post build summary
        run: echo '${{ toJSON(needs.build.outputs) }}'


